STATUS_ACTIVE = 1
STATUS_INACTIVE = 2
STATUS_PENDING = 3
STATUS_FAILED = 9
STATUS_DONE = 10
STATUS_DELETED = 11

TAP_ACCESS_PUBLIC = 1
TAP_ACCESS_SUBSCRIBERS = 2
TAP_ACCESS_PRIVATE = 3

DATA_STATE_NOT_MATERIALIZED = 1
DATA_STATE_MATERIALIZED = 2
DATA_STATE_READ_ONLY = 3
DATA_STATE_REQUEST_REBUILD = 4
DATA_STATE_REBUILDING = 5
DATA_STATE_REQUEST_TRUNCATE = 6
