STATUS_ACTIVE = 1
STATUS_INACTIVE = 2
STATUS_PENDING = 3
STATUS_FAILED = 9
STATUS_DONE = 10
STATUS_DELETED = 11

STATUS_FLOW_OPEN = 1
STATUS_FLOW_PROCESSING = 2
STATUS_FLOW_PROCESSED = 3
STATUS_FLOW_COMMITTED = 4
STATUS_FLOW_ABORTED = 11

TAP_ACCESS_PUBLIC = 1
TAP_ACCESS_SUBSCRIBERS = 2
TAP_ACCESS_PRIVATE = 3

DATA_STATE_NOT_MATERIALIZED = 1
DATA_STATE_MATERIALIZED = 2
DATA_STATE_READ_ONLY = 3
DATA_STATE_REQUEST_REBUILD = 4
DATA_STATE_REBUILDING = 5
DATA_STATE_REQUEST_TRUNCATE = 6

TRX_TYPE_FLOW = 1
TRX_TYPE_CREDIT = 2

FLOW_UPLOAD = 1
FLOW_DOWNLOAD = 3

TAG_ENTITY_TYPE = 1
TAG_PRIVACY_TYPE = 2
TAG_FEED_TYPE = 3

DISPLAY_MODE_BUYER = 1
DISPLAY_MODE_SELLER = 2
DISPLAY_MODE_FULL = 3
